# SQLite version 3.x
#   gem install sqlite3
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#development:

 # adapter: postgresql
  #encoding: unicode
  #username: postgres
  #password: password
  #host: 127.0.0.1
  #port: 5432
  #database: personald
  #pool: 5
  #timeout: 5000


#test:
 # adapter: postgresql
  #encoding: unicode
  #username: postgres
  #password: password
  #host: 127.0.0.1
  #port: 5432
  #database: personalt
  #pool: 5
  #timeout: 5000

#production:
 #   adapter: postgresql
  #  encoding: unicode
   # username: postgres
    #password: password
    #host: 127.0.0.1
    #port: 5432
    #database: personalp
    #pool: 5
    #timeout: 5000




 development:

   adapter: oracle_enhanced
   pool: 5
   timeout: 5000
   database: //172.25.10.3:1521/DBDES
   username: DBPERSONAL
   password: ORACLE

   production:
      adapter: postgresql
      encoding: unicode
      username: postgres
      password: password
      host: 172.25.10.6
      port: 3
      database: personalp
      pool: 5
      timeout: 5000
